baseURL = 'https://www.linuxguru.net/'
languageCode = 'en-us'
title = 'DevOps Thoughts and Ruminations'
theme = 'mainroad'
publishDir = "docs"
googleAnalytics = "G-VTZZVQGDLY"

[markup.goldmark.renderer]
unsafe = true

menu = [ "main" ]

[Author]
  name = "James Blackwell"
  bio = "Making stuff that makes stuff"
  avatar = "img/me.png"

[Params]
  description = "Thoughts and Ruminations from the world of Devops"
  copyright = "James Blackwell" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news", "notes"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "img/me.png" # Logo image. Path relative to "static"
  title = "Naming is hard" # Logo title, otherwise will use site title
  subtitle = "Thoughts and Ruminations from the world of Devops"

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "tehjaydeebee"
  twitter = "j_wb"
  linkedin = "tehjaydeebee"
  github = "jdblack"
  email = "jblack@linuxguru.net"

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["time","social", "recent", "categories", "taglist", "search"]


#[[Params.widgets.social.custom]]
#  title = "Youtube"
#  url = "https://www.youtube.com/@jblacktube"
#  icon = "youtube.svg" # Optional. Path relative to "layouts/partials"
#  rel = "noopener noreferrer" # Set to false to remove the rel attribute

[Params.widgets.search]
  url = "https://google.com/search"
  [Params.widgets.search.input]
    name = "sitesearch"
    pre = ""

[[Params.widgets.social.custom]]
  title = "My Resume"
  url = "https://for-your-perusal.s3.amazonaws.com/JamesBlackwell.Resume.pdf"
  icon = "resume.svg"

